[project]
name = "pricheta-bot"
version = "1.0"
description = "Pricheta's telegram bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.25.0",
    "aiogram-input>=3.1.0",
    "aiohttp>=3.13.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pytest>=9.0.2",
    "pytest-coverage>=0.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.2",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "ANN201",  # Публичные функции
    "ANN202",  # Приватные функции
    "ANN204",  # Специальные методы (__init__ и др.)
    "ANN205",  # Статические методы
    "ANN206",  # Методы класса
]
